name: flutter_newspaper_app
description: Flutter Newspaper App

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  equatable: ^2.0.5
  json_annotation: ^4.0.1
  json_serializable: ^6.3.1
  rxdart: ^0.27.5
  intl: ^0.17.0
  flutter_ds_bfi: ^0.0.2+26

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  change_app_package_name: ^1.1.0
  test: any

flutter:
  uses-material-design: true
  # Remove Comment if you add Asset for this Project
  # assets:
  #   - assets/imgs/
  fonts:
    - family: Poppins
      fonts:
        - asset: packages/flutter_ds_bfi/fonts/Poppins-Regular.ttf
        - asset: packages/flutter_ds_bfi/fonts/Poppins-Bold.ttf
        - asset: packages/flutter_ds_bfi/fonts/Poppins-Italic.ttf
        - asset: packages/flutter_ds_bfi/fonts/Poppins-Regular.ttf
