// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdShnqeEeGNqh-OMMUvHqFdMJABZdzskQ',
    appId: '1:599351373847:android:793774b35f9cb531ab6c52',
    messagingSenderId: '599351373847',
    projectId: 'flutter-newspaper-apps',
    storageBucket: 'flutter-newspaper-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0VhjUpF9_mi4tQ-_dwFDGpvcI8eyiNBM',
    appId: '1:599351373847:ios:e87a234482b89bd2ab6c52',
    messagingSenderId: '599351373847',
    projectId: 'flutter-newspaper-apps',
    storageBucket: 'flutter-newspaper-apps.appspot.com',
    androidClientId: '599351373847-a1kefa4tlcmck84qad1ogd98b09of0eu.apps.googleusercontent.com',
    iosClientId: '599351373847-vcnhmejb3htoqr5rqiiqp4vd3v26m301.apps.googleusercontent.com',
    iosBundleId: 'bfi.id.flutterBfiBoilerplate',
  );
}
